Feat/get user data
TheBridge-FullStackDeveloper/tuttifrutti-store-back-2021 pull request #10
Opened 2021-10-06 17:27 UTC by clgsg

Test from http://localhost:3000/user
Variables are temporary. Values from access token should be used instead.

2021-10-06 19:08 UTC, elisasoto approved these changes

2021-10-07 17:38 UTC, Riftland requested changes

2021-10-07 17:38 UTC, Riftland commented on services/users/getUser.js
> +	const { username } = req.query;
Pero tened en cuenta que igual de temporal que su uso en la query

2021-10-07 17:38 UTC, Riftland commented on query/user.js
> +		const { rows: user } = await db.query(sql`
Mejor usad `db.maybeOne` o `db.one` en lugar de `db.query`. Si solo queréis un usuario, mejor que os devuelva un objeto directamente en lugar de un array de un solo elemento

2021-10-07 17:38 UTC, Riftland commented on services/users/getUser.js
> +	const [result] = await getUserData(db, {username})
Si cambiais la función de la consulta, recordad que aquí no os devolvería un array, sino un objeto o `null` en caso de no  encontrar ninguno

2021-10-11 16:44 UTC, merged