Feat/add payment method
TheBridge-FullStackDeveloper/tuttifrutti-store-back-2021 pull request #11
Opened 2021-10-06 18:08 UTC by maidersonn

Ticket: https://trello.com/c/lTQEG1Zg

2021-10-06 18:36 UTC, elisasoto approved these changes

2021-10-06 19:04 UTC, elisasoto requested changes

2021-10-06 19:04 UTC, elisasoto commented on query/cards.js
> +    return rows;
creo que falta referenciar el usuario al que se guardará la información. Justo como el ejemplo que pasó hace un momento Jorge, por lo tatno habría que checar qué user quiere agregar una tarjeta y después asignarle el id no?

```
 VALUES
        (( select id from users where username = 'jnova' ), 'VISA', '0001','12/04', 'Diego González'),
```

2021-10-06 19:06 UTC, elisasoto reviewed
puedes agregar la colección de postman editada con las consultas?

2021-10-06 19:31 UTC, diegoztrombone commented on query/cards.js
> +    return rows;
Lo mismo que Elisa, he subido PR con la modificación en el archivo de insercción, para que se referencie tarjeta e id de usuario

2021-10-08 16:01 UTC, diegoztrombone approved these changes

2021-10-11 17:04 UTC, clgsg requested changes
Apart from the 'pruba' file, it looks ok to me.

2021-10-11 17:04 UTC, clgsg commented on pruba.js
> +console.log(token);
Delete this file (function  used in  helpers/jwt)

2021-10-11 17:18 UTC, Girgetto commented
I've made some little changes:

1. Removed `pruba.js`
2. Removed `console.log`
3. Added a [condition](https://github.com/TheBridge-FullStackDeveloper/tuttifrutti-store-back-2021/pull/11/commits/8563c5f515b178b52765d827b4b85c693011d47a#diff-0a93607168278fe6c3be799f31f533678c87a0099eb621bd63c5d68453d22bdaR8) to check whether `card_number` is a type string or not, if not it throws an error to avoid app break
4. Resolved conflicts with `index.js`

2021-10-11 17:18 UTC, Girgetto approved these changes

2021-10-11 17:19 UTC, merged