Feat/get order by date
TheBridge-FullStackDeveloper/tuttifrutti-store-back-2021 pull request #25
Opened 2021-10-19 17:48 UTC by Janton2021

2021-10-19 18:19 UTC, Protero approved these changes, later dismissed

2021-10-19 19:01 UTC, Riftland requested changes

2021-10-19 19:01 UTC, Riftland commented on services/index.js
> +<<<<<<< HEAD
Cuidado con estas líneas, habéis dejado lo que os pone VSC para resolver los conflictos

2021-10-19 19:01 UTC, Riftland commented on services/index.js
> +=======
Mismas líneas

2021-10-19 19:01 UTC, Riftland commented on services/index.js
> +>>>>>>> develop
Mismas líneas, además, las rutas están duplicadas

2021-10-19 19:01 UTC, Riftland commented on services/orders/get-order-by-date.js
> +        featured: result.rows,
Por qué la propiedad de `data` es `featured` si no son los productos destacados? Cuidado al copiar/pegar 😈 
Cambiad el nombre de la propiedad por otro con más sentido para el contexto de la funcionalidad que estáis haciendo. De paso cambiad también el de `coincidences` por `total` o similar

2021-10-19 19:01 UTC, Riftland commented on services/orders/index.js
> +  router.get("/ordersByDate", authorization, require("./get-order-by-date")(db));
Mal nombre para una ruta si estamos haciendo una API Rest, como sería un "filtrado" de todos los pedidos, lo suyo sería trabajar directamente sobre la ruta ya creada de `/orders`. No obstante podéis hacer una adicional pero deberíais cambiarle el nombre

2021-10-19 19:06 UTC, Janton2021 commented on services/index.js
> +>>>>>>> develop
En develop está mal, en nuestra pull request se corrige

2021-10-19 19:10 UTC, Riftland commented on services/index.js
> +>>>>>>> develop
Si aparece en verde en la pr, significa que se añade, tened cuidado por si habéis hecho un merge y siguen estando!

2021-10-19 21:24 UTC, maidersonn commented on services/orders/get-order-by-date.js
> +    const username = res.locals.user
Aquí me parece que no se coge el username. Se debería poner el username con llaves : const {username}   o sino poner res.locals.user.username.

2021-10-20 16:33 UTC, maidersonn approved these changes
Para que luego no espereís, ya teneís el aprobado.

2021-10-20 16:50 UTC, merged