Registro de usuario
TheBridge-FullStackDeveloper/tuttifrutti-store-back-2021 pull request #9
Opened 2021-10-05 22:55 UTC by TommyTraddles

Based on: https://trello.com/c/a54RNWea/10-registro-de-usuario

routing:
- `POST url:port/register` or import postman
- mandatory fields: username, hash, email

comments:
- deleting some user SQL user's table constraints ( `not null` for creating user )
- creating `npm run db:reset` (drop + create + seed )
- adding `postman.json` query
- creating gmail for testing (**info on trello**)
- updating `.env` file (**info on trello**)

for testing:
- update .env file
- setup postman  -> use a real email
- review DB on Docker (pre email, and post email)

2021-10-06 14:51 UTC, elisasoto approved these changes
🚀

2021-10-06 19:22 UTC, Riftland requested changes

2021-10-06 19:22 UTC, Riftland commented on helpers/mailer/confirmation.js
> +}
De base es la misma configuración, con lo que mejor si metes esa configuración en `/config/mailer` y también puedes tener solo una función de creación de templates y que, a través de argumentos, realmente configure el correo. Ahora mismo no habría mucha diferencia si solo tienes dos templates de los correos diferentes en un directorio `/templates`

2021-10-06 19:22 UTC, Riftland commented on services/auth/register.js
> +  const { email, username, hash } = req.body
No debería llamarse la variable `hash` así, mejor `password`, denominar a algo `hash` implica que ya se ha tokenizado o se ha hecho "indescifrable"

2021-10-06 19:22 UTC, Riftland commented on query/auth.js
> +  return await db.query(sql`
Como sabes que solo te tiene que salir un usuario, mejor `db.maybeOne` o `db.one` que `db.query`

2021-10-06 19:22 UTC, Riftland commented on query/auth.js
> +    const {rowCount} = await userExist(db, { email, username })
Si cambias lo del comentario anterior y no encuentra ninguno, la respuesta será `null`, con lo que no podrás desestructurar la respuesta en caso de no encontrar ninguno y dará error

2021-10-06 19:22 UTC, Riftland commented on query/auth.js
> +    return rows
Si haces varios pasos, siempre mejor intenta transacciones `db.transaction`. También va para la consulta anterior

2021-10-06 19:22 UTC, Riftland commented on helpers/mailer/activation.js
> +      </a>
Cuando lo he probado, así el botón no me ha redirigido a ningún sitio. Mejor pon el enlace directamente con algún texto

2021-10-07 19:03 UTC, TommyTraddles commented on services/auth/register.js
> +  const { email, username, hash } = req.body
Resuelto

2021-10-07 19:03 UTC, TommyTraddles commented on helpers/mailer/confirmation.js
> +}
Resuelto (?)

2021-10-07 19:07 UTC, TommyTraddles commented on query/auth.js
> +  return await db.query(sql`
Resuelto

2021-10-07 19:08 UTC, TommyTraddles commented on query/auth.js
> +    const {rowCount} = await userExist(db, { email, username })
Resuelto

2021-10-07 19:12 UTC, TommyTraddles commented on query/auth.js
> +    return rows
Resuelto

2021-10-07 19:12 UTC, TommyTraddles commented on helpers/mailer/activation.js
> +      </a>
Resuelto

2021-10-11 17:24 UTC, clgsg approved these changes
With applied changes (as per Molpe's suggestion), LGTM 👌🏼

2021-10-13 16:54 UTC, merged